### ISSUE TITLE
ReferenceTests is not compatible with ImageInTerminal `0.5.0`

### ISSUE THREAD

**Issue by adrhill** [JuliaTesting/ReferenceTests.jl#116]
ReferenceTests makes use of `ImageInTerminal`'s `encodeimg`, which appears to have been deprecated in ImageInTerminal `0.5.0`.
https://github.com/JuliaTesting/ReferenceTests.jl/blob/852eba73a7401ba9d505f7c4ef169ae1aa5ae17a/src/fileio.jl#L59

However ImageInTerminal `0.5.0` is allowed in `[compat]`:
https://github.com/JuliaTesting/ReferenceTests.jl/blob/852eba73a7401ba9d505f7c4ef169ae1aa5ae17a/Project.toml#L28

This currently breaks CI of packages using ReferenceTests. @t-bltg

**Comment by t-bltg** [comment]
Sorry about that. Hum it seems that ci wasn't even gree before merging https://github.com/JuliaTesting/ReferenceTests.jl/pull/115.

@oxinabox , @johnnychen94 , should we yank and rework that release since it already affects users ?

The circular dependency makes it not ideal for testing before releasing...

**Comment by juliohm** [comment]
I confirm that the issue is affecting my tests as well.

Em ter., 9 de ago. de 2022 19:09, t-bltg ***@***.***>
escreveu:

**Comment by t-bltg** [comment]
Yeah if someone could yank that one quickly, I'll sort it out tomorrow (afk right now).

**Comment by IanButterworth** [comment]
https://github.com/JuliaRegistries/General/pull/65983

**Comment by IanButterworth** [comment]
Yanked

**Comment by johnnychen94** [comment]
The next question is, will a ReferenceTests breaking release `0.10` be acceptable?

I know many people don't hardcode the `compat` section for their test dependencies, so they'll still see their CI red if some of the test depend on the text reference version of an image, e.g., `@test_reference "imagetest1.txt" testimage("cameraman")`.

**Comment by t-bltg** [comment]
> I know many people don't hardcode the compat section for their test dependencies

I guess the root cause of not writing test `[compat]` is the [new test depencencies spec](https://pkgdocs.julialang.org/v1/creating-packages/#Test-specific-dependencies-in-Julia-1.2-and-above) (`test/Project.toml`) not being complete, over the [old one](https://pkgdocs.julialang.org/v1/creating-packages/#Test-specific-dependencies-in-Julia-1.0-and-1.1).

> The next question is, will a ReferenceTests breaking release 0.10 be acceptable?

Well ... code isn't written in stone, so we should be able to release a breaking version (minor bump).
