### ISSUE TITLE
Don't only rely on `isinteractive` for triggering the input prompt

### ISSUE THREAD

**Issue by Evizero** [JuliaTesting/ReferenceTests.jl#8]
So far this package decides whether or not an input prompt is to be triggered, by simply checking the result of `isinteractive()`. Thus, the input prompt is pretty much only displayed if the user is executing the tests from the REPL by calling `include("test/runtests.jl")`. @oxinabox made the argument that this is a bit restrictive, which I tend to agree with.

We had a brief chat in slack about it and thought of some other strategies:

- using a environment variable to detect CI
- using a environment variable to activate the input prompt
- read the callstack to see if `Pkg.test(...)` triggered the test run

**Comment by oxinabox** [comment]
Maybe an environment variable to allow the regenerate prompts isn't such a bad idea.
So defaulting to just pass, fail.
Since mistakenly regenerating a test that should fail is bad.

Conversely, maybe initial creation of the reference file should default just happen without prompt.
This would mean deleting the old reference is an easy way to have it updated via re-creation

**Comment by Evizero** [comment]
> Conversely, maybe initial creation of the reference file should default just happen without prompt.
This would mean deleting the old reference is an easy way to have it updated via re-creation

Mhm maybe. But creating a reference without visual inspection seems prone to hasty oversights.

**Comment by oxinabox** [comment]
one thing worth bearing in mind is that all the reference files do go into git.
so there is normally a second chance to check them during the PR review (even if it is a self review).
and the old ones can always be recovored from history.
